export const songs: string[] = [
    'American Idiot',
    'Enter Sandman',
    'Hunting for Witches',
    'Plug in Baby',
    'Islands',
    'Message in a Bottle',
    'Blue Orchid',
    'Holiday',
    'Californication',
    'Otherside',
    'R U Mine?',
    'Smells Like Teen Spirit',
    'Stella Was a Diver and She Was Always Down',
    'What I`ve Done',
    'Sixteen Saltines',
    'What"s my Age Again?',
    'Obstacle 1',
    'Live Forever',
    'Mr.Jones',
    'Far from Any Road'
];